import type { Metadata } from "next";
import { Oswald, Roboto } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const oswald = Oswald({ 
 subsets: ["latin"],
 weight:['200', '300' ,'400', '500' ,'600' , '700'],
 variable:'--font-Oswald',
 });
const roboto = Roboto({ 
 subsets: ["latin"],
 weight:['100', '300' ,'400', '500' ,'700' , '900'],
 variable:'--font-roboto',
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${roboto.variable} w-full max-w-[1920px] mx-auto bg-gray-200`}>
        <Header  />
        {children}
        <Footer />
      </body>
    </html>
  );
}
